/*
=========================================================
SALES ANALYSIS
=========================================================

Purpose:
- Calculate total sales
- Analyze sales by product
- Calculate product contribution to total sales
- Analyze monthly sales
- Calculate monthly contribution to total sales
- Identify the top-selling product
- Categorize sales into High, Medium, and Low
- Analyze month-over-month sales performance
*/


/*
---------------------------------------------------------
1. TOTAL SALES
What is the total sales generated from current orders?
---------------------------------------------------------
*/

SELECT
    SUM(Sales) AS Total_Sales
FROM Sales.Orders;


/*
---------------------------------------------------------
2. SALES BY PRODUCT
How are sales distributed across products?
---------------------------------------------------------
*/

SELECT
    ProductID,
    SUM(Sales) AS Total_Sales_By_Product
FROM Sales.Orders
GROUP BY ProductID
ORDER BY Total_Sales_By_Product DESC;


/*
---------------------------------------------------------
3. PRODUCT CONTRIBUTION
What percentage of total sales does each product contribute?
---------------------------------------------------------
*/

SELECT
    ProductID,
    SUM(Sales) AS Total_Sales_By_Product,
    SUM(SUM(Sales)) OVER () AS Total_Sales,
    SUM(Sales) * 100.0 /
        SUM(SUM(Sales)) OVER () AS Sales_Percentage
FROM Sales.Orders
GROUP BY ProductID
ORDER BY Sales_Percentage DESC;


/*
---------------------------------------------------------
4. MONTHLY SALES
How are sales distributed across months?
---------------------------------------------------------
*/

SELECT
    MONTH(OrderDate) AS Month_Number,
    DATENAME(MONTH, OrderDate) AS Month,
    SUM(Sales) AS Total_Sales
FROM Sales.Orders
GROUP BY
    MONTH(OrderDate),
    DATENAME(MONTH, OrderDate)
ORDER BY Month_Number;


/*
---------------------------------------------------------
5. MONTHLY SALES CONTRIBUTION
What percentage of total sales does each month contribute?
---------------------------------------------------------
*/

SELECT
    MONTH(OrderDate) AS Month_Number,
    DATENAME(MONTH, OrderDate) AS Month,
    SUM(Sales) AS Monthly_Sales,
    SUM(Sales) * 100.0 /
        SUM(SUM(Sales)) OVER () AS Sales_Percentage
FROM Sales.Orders
GROUP BY
    MONTH(OrderDate),
    DATENAME(MONTH, OrderDate)
ORDER BY Month_Number;


/*
---------------------------------------------------------
6. TOP-SELLING PRODUCT
Which product generates the most sales?
---------------------------------------------------------
*/

SELECT TOP 1
    P.Product,
    SUM(O.Sales) AS Total_Sales
FROM Sales.Orders AS O
JOIN Sales.Products AS P
    ON O.ProductID = P.ProductID
GROUP BY P.Product
ORDER BY Total_Sales DESC;


/*
---------------------------------------------------------
7. SALES CATEGORIZATION
Categorize individual orders based on sales value:

High   : Sales > 50
Medium : Sales > 20 and Sales <= 50
Low    : Sales <= 20

Then calculate total sales generated by each category.
---------------------------------------------------------
*/

SELECT
    CASE
        WHEN Sales > 50 THEN 'High'
        WHEN Sales > 20 THEN 'Medium'
        ELSE 'Low'
    END AS Sales_Category,
    SUM(Sales) AS Total_Sales
FROM Sales.Orders
GROUP BY
    CASE
        WHEN Sales > 50 THEN 'High'
        WHEN Sales > 20 THEN 'Medium'
        ELSE 'Low'
    END
ORDER BY Total_Sales DESC;


/*
---------------------------------------------------------
8. MONTH-OVER-MONTH SALES PERFORMANCE
Calculate the percentage change in sales between
the current month and previous month.
---------------------------------------------------------
*/

SELECT
    Month_Number,
    Month,
    Monthly_Sales,
    Previous_Month_Sales,
    (Monthly_Sales - Previous_Month_Sales) * 100.0 /
        NULLIF(Previous_Month_Sales, 0) AS Percentage_Change
FROM
(
    SELECT
        MONTH(OrderDate) AS Month_Number,
        DATENAME(MONTH, OrderDate) AS Month,
        SUM(Sales) AS Monthly_Sales,
        LAG(SUM(Sales)) OVER (
            ORDER BY MONTH(OrderDate)
        ) AS Previous_Month_Sales
    FROM Sales.Orders
    GROUP BY
        MONTH(OrderDate),
        DATENAME(MONTH, OrderDate)
) AS T
ORDER BY Month_Number;
