```sql id="p4lqk1"
/*
=========================================================
SALESPERSON ANALYSIS
=========================================================

Purpose:
- Analyze sales generated by each salesperson
- Rank salespeople based on total sales
*/


/*
---------------------------------------------------------
1. SALES BY SALESPERSON
How much sales did each salesperson generate?
---------------------------------------------------------
*/

SELECT
    E.EmployeeID,
    E.FirstName,
    E.LastName,
    SUM(O.Sales) AS Total_Sales
FROM Sales.Employees AS E
JOIN Sales.Orders AS O
    ON E.EmployeeID = O.SalesPersonID
GROUP BY
    E.EmployeeID,
    E.FirstName,
    E.LastName
ORDER BY Total_Sales DESC;
```
